### ISSUE TITLE
Problems With Injecting

### ISSUE THREAD

**Issue by Scrapmine** [HorionContinued/Injector#13]
The game crashes when injecting dll.
If this is the wrong repository please give me the link to the correct one.

**Comment by XPower7125** [comment]
same issue on latest MC release and latest Horion

**Comment by richardletshacks** [comment]
This is not an injector-related issue.
The mod is currently not updated to the latest version of the game, use 1.19.50/51 to continue using the mod.
Please refrain from creating new issues related to the mod.

**Comment by Scrapmine** [comment]
ok
