### ISSUE TITLE
.gamemode 3

### ISSUE THREAD

**Issue by ExcludedBliss** [HorionContinued/Injector#15]
After going into Gamemode 1 and then back to 3 you will not take damage and you will not use items when placing them. if you go into gamemode 2 before going into gamemode 1 you will take damage and place stuff like normal but taking something out of a item frame will delete it.

**Comment by richardletshacks** [comment]
Hey, your issue is unrelated to the injector. Please report bugs/ask for help related to Horion in our [discord](https://horion.download/discord).
