### ISSUE TITLE
Structure Locating Bug

### ISSUE THREAD

**Issue by idodumbstuff** [HorionContinued/Injector#25]
Can't locate any structures in the nether or end besides end_city (which causes whole game to crash if used in nether).

**Comment by teteus420** [comment]
everybody gangsta till they close it without responding

**Comment by richardletshacks** [comment]
this is the repository of our injector.
for bugs in the mod itself, join our [discord](https://horion.download/discord) and post it there.

**Comment by teteus420** [comment]
so why you guys have a issues page? 1.9 GDPS for example doesnt have one
