### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by Auserath** [HorionContinued/Injector#30]
Hello, there are currently no updates for horion on the 1.21.44 version of minecraft, it only is supported by the 1.21.30 and 1.21.31. I have waited a week and a half for this issue since last time it got fixed within the day but it seems that this isn't the case so I thought it would be good to bring it here. I have already tried redownloading it, removing it then downloading, restarting my computer, all of that good jazz lmao. 
![Minecraft 11_2_2024 11_33_25 AM](https://github.com/user-attachments/assets/2fd18660-57f9-418b-87ea-0ea40b95a860)

**Comment by richardletshacks** [comment]
"Please wait for Horion to update."

**Comment by 2cool4tech** [comment]
Horion isn't working!!!!!

**Comment by dantheman4700** [comment]
I'm left speechless, this is maybe one of the dumbest github issues I've ever seen posted. It literally says "wait for update".
